
#### Deconvolution model using 19 tumors X.matrix generated by DTD ####


# Load the DTD tutorials data from *DTD tutorials.R* file

DTD_data <- readRDS("Data/DTD tutorials.rds")
X.matrix_train <- DTD_data$X_matrix
training_data_dtd <- DTD_data$train
DTD_train_expres <- DTD_data$train$mixtures
DTD_train_pheno <- DTD_data$train$quantities


# Create a vector containing features from X.matrix

select_features <- rownames(X.matrix_train)

# Train deconvolution model using X.matrix #

start_tweak <- rep(1, length(select_features))
names(start_tweak) <- select_features

# Deconvolute the model using X.matrix data 

library(DTD)

set.seed(100)

bulk_model <- train_deconvolution_model(
                                        tweak = start_tweak,
                                        X.matrix = X.matrix_train,
                                        train.data.list = training_data_dtd,
                                        test.data.list = training_data_dtd,
                                        estimate.c.type = "direct",
                                        use.implementation = "cpp"
                                        )

# Estimate cell-type proportion matrix using new deconvolution model

estimate_c_x.train_model <- estimate_c(
                          X.matrix = X.matrix_train,
                          new.data = DTD_data$test$mixtures,
                          DTD.model = bulk_model,
                          estimate.c.type = "direct")

# Correlation between estimated_c and DTD_train_pheno

cor_estc_dtd_testpheno <- mapply(cor, as.data.frame(t(DTD_data$test$quantities)), 
                                  as.data.frame(t(estimate_c_x.train_model)))
cor_estc_dtd_testpheno

decon_x.matrix_data <- list("DTD_sc_reference" = cor_estc_dtd_testpheno)

saveRDS(decon_x.matrix_data, "Data/decon_x.matrix_data")
